### ISSUE TITLE
Attribute (url) does not pass the type constraint in Synopsis

### ISSUE THREAD

**Issue by szabgab** [worthmine/Text-vCard-Precisely#20]
I tried the code from the synopsis and this line:

```
$vc->url({ content => 'https://twitter.com/worthmine', types => ['twitter'] }); # for URL param
```

Got me this error:

```
Attribute (url) does not pass the type constraint because: Validation failed for 'URLs' with value HASH(0x5587a05eed50) at accessor Text::vCard::Precisely::V3::url (defined at /home/gabor/perl5/lib/perl5/Text/vCard/Precisely/V3.pm line 572) line 8
	Text::vCard::Precisely::V3::url('Text::vCard::Precisely=HASH(0x55879e439fa8)', 'HASH(0x5587a05eed50)') called at b.pl line 29
```

These worked, but I don't know what is the difference and which is the correct one.
```
$vc->url('https://twitter.com/worthmine');
$vc->url('https://twitter.com/worthmine', 'twitter');
```

**Comment by worthmine** [comment]
thank you for pointing out!

It may be my miswriting and give me a few days to correct this.

**Comment by worthmine** [comment]
It was a bug around url param and I've fixed just now.

being wander 'which is the correct one?' is nonsense with this module because this has [type coercions](https://metacpan.org/pod/Moose::Util::TypeConstraints#Type-Coercion-Constructors).

I can say that all paramaters that doesn't work such you thought are wrong.

**Comment by Mokeev** [comment]
Hello,
`$vc->url(
[
   { content => 'https://twitter.com/worthmine', types => ['twitter'] },
   { content => 'https://github.com/worthmine' },
]
);
`
Gives:
Attribute (types) does not pass the type constraint because: Validation failed for 'Types' with value ARRAY(0x561da760fda0) at constructor Text::vCard::Precisely::V3::Node::URL::new (defined at /usr/local/lib64/perl5/5.32/Text/vCard/Precisely/V3/Node/URL.pm line 31) line 85
        Text::vCard::Precisely::V3::Node::URL::new('Text::vCard::Precisely::V3::Node::URL', 'HASH(0x561da78eb2a0)') called at /usr/local/lib64/perl5/5.32/Text/vCard/Precisely/V3.pm line 558
        Text::vCard::Precisely::V3::__ANON__('ARRAY(0x561da78eb318)') called at /usr/lib64/perl5/vendor_perl/5.32/x86_64-linux/Moose/Meta/TypeCoercion.pm line 65
        Moose::Meta::TypeCoercion::__ANON__('ARRAY(0x561da78eb318)') called at accessor Text::vCard::Precisely::V3::url (defined at /usr/local/lib64/perl5/5.32/Text/vCard/Precisely/V3.pm line 560) line 5
        Text::vCard::Precisely::V3::url('Text::vCard::Precisely=HASH(0x561da78eb528)', 'ARRAY(0x561da78eb318)') called at vcard.pl_dev line 84


What is wrong?

**Comment by worthmine** [comment]
@Mokeev 
Thanks for reporting.
I'm sorry that I don't have enough time to fix it ASAP.

Please try below:
(It was just trimed brakets for ArrayRef)
```perl
$vc->url( { content => 'https://twitter.com/worthmine', types => ['twitter'] }, { content => 'https://github.com/worthmine' } );
```

Moose can ignore that attribute(s) is an Array or ArrayRef with Coercing.
So it might be a fault of mine for definitions around those.

**Comment by worthmine** [comment]
@Mokeev 
I'm sorry that I had a wrong replying.

```perl
$vc->url( { content => 'https://twitter.com/worthmine', types => ['twitter'] }, { content => 'https://github.com/worthmine' } );
```

it doesn't work because coercions will catch the first HashRef from given list, However,

```perl
$vc->url( [ { content => 'https://twitter.com/worthmine', types => ['twitter'] }, { content => 'https://github.com/worthmine' }, ] ); 
```

Gives no errors with latest version(0.28), so I think it was a fixed bug.
